<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.6">
  <POU Name="MAIN" Id="{8e233c46-3dcc-438d-96d2-34061c6cb05e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	n: INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[n := n+1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>